#!/usr/bin/env python3
"""List hole packages that are not playable, using the generator's own checks. Read-only.

  python scan_playability.py <holes_root> [--json]     (scan_launch.py is the same scan under its old name)

Rated packages are immutable, so a hole generated by an older GENERATOR_VERSION cannot be re-sculpted. This lists
the ones whose tee shot hits the ground (TH-5, before v4) or whose green is too steep to putt on (Q5-1: pond banks
tilted greens to 15 % before v5), so the trainer can mark them unplayable and keep them out of the top-holes ranking.
Prints one line per failing hole, then a summary (or one JSON object with --json).
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
from shapely.geometry import LineString, Point

import _prep  # noqa: F401
from generate import GEN_FILE
from hole_package import area_polygons, read_heights, read_hole
from validate import green_issues, green_slopes, launch_issues, launch_overshoot


def launch_profile(package_dir: Path, hole: dict | None = None) -> dict[str, tuple[np.ndarray, np.ndarray]]:
    """validate.launch_overshoot for one package on disk: {line name: (s, over)}."""
    hole = hole or read_hole(package_dir)
    path = LineString(np.asarray(hole["holePath"]["points"], dtype=float).reshape(-1, 2))
    return launch_overshoot(path, read_heights(package_dir, hole), hole["sizeMeters"])


def green_profile(package_dir: Path, hole: dict | None = None) -> tuple[float, float] | None:
    """validate.green_slopes for one package on disk: (grade near the pin, steepest grade on the putting surface),
    on the green nearest the pin. None: the package has no green."""
    hole = hole or read_hole(package_dir)
    pin = Point(hole["pin"]["x"], hole["pin"]["y"])
    greens = [poly for surface, poly in area_polygons(hole) if surface == "green"]
    if not greens:
        return None
    green = min(greens, key=pin.distance)
    return green_slopes(green, pin, read_heights(package_dir, hole), hole["sizeMeters"])


def scan_package(package_dir: Path) -> list[str]:
    """Every playability problem of one package on disk (empty = the tee shot clears the ground and the green is
    puttable)."""
    hole = read_hole(package_dir)
    slopes = green_profile(package_dir, hole)
    return launch_issues(launch_profile(package_dir, hole)) + (green_issues(*slopes) if slopes else [])


def generator_version(package_dir: Path) -> int | None:
    gen = package_dir / GEN_FILE
    return json.loads(gen.read_text()).get("generatorVersion") if gen.exists() else None


def scan(root: Path) -> dict:
    failing, checked, unreadable = {}, 0, []
    for package_dir in sorted(d for d in root.iterdir() if (d / "hole.json").exists()):
        try:
            issues = scan_package(package_dir)
        except (OSError, KeyError, ValueError) as e:
            unreadable.append(f"{package_dir.name}: {e}")
            continue
        checked += 1
        if issues:
            failing[package_dir.name] = {"generatorVersion": generator_version(package_dir), "issues": issues}
    return {"checked": checked, "failing": failing, "unreadable": unreadable}


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("root", type=Path, help="folder of hole packages (e.g. the trainer's /data/holes)")
    p.add_argument("--json", action="store_true")
    args = p.parse_args()
    result = scan(args.root)
    if args.json:
        print(json.dumps(result, indent=1))
        return
    for hid, info in result["failing"].items():
        print(f"{hid} (v{info['generatorVersion']}): {'; '.join(info['issues'])}")
    for line in result["unreadable"]:
        print(f"unreadable {line}")
    print(f"{len(result['failing'])} of {result['checked']} holes fail the playability checks (tee shot, green)")


if __name__ == "__main__":
    main()
